# Generated by Django 4.2.3 on 2023-09-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nivel',
            new_name='nivelid',
        ),
    ]
