# Generated by Django 4.2.3 on 2023-09-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_nivelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nivelmodel'),
        ),
    ]
