# Generated by Django 4.2.3 on 2023-09-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_nivelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userempresamodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='auth_users', to='auth.group', verbose_name='groups'),
        ),
    ]
