# Generated by Django 4.2.3 on 2023-08-14 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0017_remove_lotemodel_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagamento_atribuicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('data_do_pagamento', models.DateTimeField(auto_now=True)),
                ('valor_do_pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_de_referencia', models.IntegerField()),
                ('status_do_pagamento', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='Pendente', max_length=50)),
                ('atribuicao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.loteatribuicaomodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
