# Generated by Django 4.2.3 on 2023-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento_atribuicao',
            name='status_do_pagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=50),
        ),
    ]
