# Generated by Django 4.2.3 on 2023-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_pagamento_atribuicao_status_do_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento_atribuicao',
            name='data_do_pagamento',
            field=models.DateField(auto_now=True),
        ),
    ]
