# Generated by Django 4.2.3 on 2023-08-15 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0030_alter_empresamodel_principais_funcionarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoGeralModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=50)),
                ('tipo_notificacao', models.CharField(max_length=50)),
                ('assunto', models.TextField(default='')),
                ('data', models.DateField(default=0)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacaoEmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=50)),
                ('tipo_notificacao', models.CharField(max_length=50)),
                ('assunto_empresa', models.TextField(default='')),
                ('data', models.DateField(default=0)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='', max_length=50)),
                ('empresaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
