# Generated by Django 4.2.3 on 2023-08-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_rename_empresaid_notificacaoempresamodel_empresa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacaoempresamodel',
            old_name='empresa_id',
            new_name='nif_empresa',
        ),
    ]
