# Generated by Django 4.2.3 on 2023-08-08 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impostos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=10)),
                ('descricao', models.TextField(default='Aqui descreva o tipo de imposto a pagar')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('latitude', models.CharField(max_length=9, null=True)),
                ('longitude', models.CharField(max_length=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacaoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='DEscreva o genero da notificacao')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(default='DEscreva o genero da notificacao')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('descricao', models.TextField(choices=[('fazendeiro', 'Fazendeiro'), ('Financiador', 'Financiador')], default='fazndeiro')),
                ('nif', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/images/Logo/')),
                ('documentos', models.ImageField(blank=True, null=True, upload_to='static/documentos/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.IntegerField()),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Sobre_nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.IntegerField()),
                ('observacao', models.TextField()),
                ('orcamento', models.DecimalField(choices=[('min', 'Min'), ('max', 'Max')], decimal_places=2, default='Min', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('Descricao', models.TextField()),
                ('area', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=8)),
                ('estado', models.CharField(choices=[('desocupado', 'Desocupado'), ('ocupado', 'Ocupado')], default='desocupado', max_length=25)),
                ('localizacaoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.localizacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpostoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='Pendente', max_length=100)),
                ('impostoid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.impostos')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoLote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
                ('data_atribuicao', models.DateTimeField(auto_now=True)),
                ('data_de_saida', models.DateTimeField(auto_now_add=True)),
                ('loteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
