# Generated by Django 4.2.3 on 2023-08-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_perfil_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacaoempresa',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='notificacaoempresa',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='notificacaoempresa',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='historicolote',
            name='empresaid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impostoempresa',
            name='empresasid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacaoempresa',
            name='empresaid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacaoempresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
