# Generated by Django 4.2.3 on 2023-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_notificacaoempresa_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
