# Generated by Django 4.2.3 on 2023-08-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfil_nome_completo_perfil_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='documentos',
            field=models.PositiveSmallIntegerField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
