# Generated by Django 4.2.3 on 2023-08-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_perfil_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='documentos',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
