# Generated by Django 4.2.3 on 2023-08-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_perfil_documentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicolote',
            old_name='empresaid',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='historicolote',
            old_name='loteid',
            new_name='lote',
        ),
        migrations.RenameField(
            model_name='impostoempresa',
            old_name='empresasid',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='impostoempresa',
            old_name='impostoid',
            new_name='imposto',
        ),
        migrations.RenameField(
            model_name='notificacaoempresa',
            old_name='empresaid',
            new_name='empresa',
        ),
    ]
