# Generated by Django 4.2.3 on 2023-08-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_empresaid_historicolote_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicolote',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
        ),
        migrations.AlterField(
            model_name='historicolote',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lote'),
        ),
        migrations.AlterField(
            model_name='impostoempresa',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
        ),
        migrations.AlterField(
            model_name='impostoempresa',
            name='imposto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.impostos'),
        ),
        migrations.AlterField(
            model_name='notificacaoempresa',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
        ),
    ]
