# Generated by Django 4.2.3 on 2023-08-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_historicolote_empresa_alter_historicolote_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='nome_lote',
            field=models.CharField(default='Nome', max_length=50),
        ),
    ]
