"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import os
import sys
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/
def add_folder(folder):
    UTILS_DIR = os.path.join(BASE_DIR, '{}'.format(folder)) 
    sys.path.append(UTILS_DIR)
    if folder:
        print(folder, "permissão concedida")
        
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bujl^isj#ka%_k8e!i-uj34t9-vq_sg@hoq6tm@w(1+=!ts!2a'
MAPBOX_API_KEY = 'pk.eyJ1IjoicGF1bGlub3R5b3ZhIiwiYSI6ImNsbmN2d2ZxdzA5dHQybGxsanZqbzQ2d2MifQ.HzV26x7iCbt10qWIcKqq7Q'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
APPEND_SLASH=True

ALLOWED_HOSTS = ["*"]

# dispositivos aceites
# CORS_ALLOWED_ORIGINS = [
#     #"http://localhost:4000",
#     "http://192.168.68.95:3000",
# ]
# Outras configurações do CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS","Retrieve"]
CORS_ALLOWED_HEADERS = ["*"]
CORS_EXPOSE_HEADERS = []
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_ALLOW_ALL_ORIGINS = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # "app",
    "empresas",
    "lotes",  
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    # 'qrcode',
    'users',
    'django_extensions',
    # 'tipo'

]

AUTH_USER_MODEL = 'users.User'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [Path("templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "Zeeplus",
#         "USER": "root",
#         "PASSWORD": "",
#         "HOST": "localhost",
#         "PORT": "3306",

#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'pt-pt'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,"staticfiles")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    # 'DEFAULT_RENDERER_CLASSES': [
    #      'rest_framework.renderers.JSONRenderer',
    #     #  'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    # ],
    
  'DEFAULT_PERMISSION_CLASSES': [
   'rest_framework.permissions.AllowAny',
],  

       'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        ],
  'DEFAULT_MIDDLEWARE':[ 
    'rest_framework.middleware.AuthenticationMiddleware' ,
    'rest_framework.middleware.AuthorizationMiddleware'
      ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=100000),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=2),
    'SLIDING_TOKEN_REFRESH_LIFETIME_ALLOW_LATE_REFRESH': False,
    'SLIDING_TOKEN_REFRESH_LIFETIME_CALCULATE': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

 

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'appkipaga@gmail.com'
# EMAIL_HOST_PASSWORD = 'uvahfxsumpbskahe'

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR,"staticfiles")
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, "static"),
    

# )
# MEDIA_ROOT = os.path.join(BASE_DIR, '')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configurar o email

# Configurações de Email
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# Credenciais de Emailsistemasiia10@gmail.com
# EMAIL_HOST_USER = "sistemasiia10@gmail.com"
# EMAIL_HOST_PASSWORD = "gcmdopcpipnusaqb"
EMAIL_HOST_USER = "mundombehenrique@gmail.com"
EMAIL_HOST_PASSWORD = "mvutkcjitokwlofn"
# Credenciais de Email


