# Generated by Django 4.2.3 on 2023-08-30 09:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0033_remove_empresamodel_principais_funcionarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteAtribuicaoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('data_de_atribuicao', models.DateField(auto_now_add=True)),
                ('valor_da_atribuicao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duracao', models.CharField(default='Em meses', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('numero_do_lote', models.IntegerField()),
                ('status', models.CharField(choices=[('desocupado', 'Desocupado'), ('ocupado', 'Ocupado'), ('em desenvolvimento', 'Em Deselvovimento')], default='desocupado', max_length=25)),
                ('data_disponibilidade', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('comprimento', models.IntegerField(default=0)),
                ('largura', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static/images/lotes/')),
                ('valor_do_lote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('informacoes_de_infraestrutura', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='pagamento_atribuicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('data_do_pagamento', models.DateField(auto_now=True)),
                ('valor_do_pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_de_referencia', models.IntegerField()),
                ('status_do_pagamento', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('cancelado', 'cancelado')], default='pendente', max_length=50)),
                ('atribuicao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.loteatribuicaomodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoteSolicitacaoModel',
            fields=[
                ('data_solicitacao', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('finalidade_de_utilizacao', models.CharField(choices=[('industrial', 'Industrial'), ('comercial', 'Comercial'), ('logistica e armazenamento', 'Logistica e Armazenamento'), ('tecnologia e inovação', 'Tecnologia e Inovação'), ('turismo e hospitalidade', 'Turismo e Hospitalidade'), ('energia', 'Energia'), ('agricultura e agroindústria', 'Agricultura e Agroindústria'), ('comércio internacional', 'Comércio Internacional'), ('indústria de pesca', 'Indústria de Pesca'), ('desenvolvimento imobiliário', 'Desenvolvimento Imobiliário')], default='Industrial', max_length=100)),
                ('status_da_solicitacao', models.CharField(choices=[('em análise', 'Em Análise'), ('rejeitada', 'Rejeitada'), ('aprovada', 'Aprovada')], default='Em Análise', max_length=25)),
                ('nif_empresa_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoteEmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('empresaid', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel')),
                ('loteId', models.ManyToManyField(default=True, to='lotes.lotemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loteatribuicaomodel',
            name='id_solicitacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.lotesolicitacaomodel'),
        ),
        migrations.AddField(
            model_name='loteatribuicaomodel',
            name='nif_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
        ),
        migrations.AddField(
            model_name='loteatribuicaomodel',
            name='numero_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel'),
        ),
        migrations.CreateModel(
            name='LocalizacaoLoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('latitude', models.CharField(max_length=35, null=True)),
                ('longitude', models.CharField(max_length=35, null=True)),
                ('loteId', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoLoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
                ('data_atribuicao', models.DateField()),
                ('data_saida', models.DateField()),
                ('nif_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel')),
                ('numero_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Descricaomodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
                ('detalhes', models.TextField()),
                ('loteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
