# Generated by Django 4.2.3 on 2023-08-10 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizacaoLoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('latitude', models.CharField(max_length=9, null=True)),
                ('longitude', models.CharField(max_length=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoteModel',
            fields=[
                ('data_disponibilidade', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('numero_do_lote', models.IntegerField()),
                ('area_do_lote', models.IntegerField()),
                ('status_do_lote', models.CharField(choices=[('desocupado', 'Desocupado'), ('ocupado', 'Ocupado'), ('em desenvolvimento', 'Em Deselvovimento')], default='desocupado', max_length=25)),
                ('Descricao', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoteSolicitacaoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('finalidade_de_utilizacao', models.CharField(default='Industrial', max_length=25, verbose_name=[('industrial', 'Industrial'), ('comercial', 'Comercial'), ('logistica e armazenamento', 'Logistica e Armazenamento'), ('tecnologia e inovação', 'Tecnologia e Inovação'), ('turismo e hospitalidade', 'Turismo e Hospitalidade'), ('energia', 'Energia'), ('agricultura e agroindústria', 'Agricultura e Agroindústria'), ('comércio internacional', 'Comércio Internacional'), ('indústria de pesca', 'Indústria de Pesca'), ('desenvolvimento imobiliário', 'Desenvolvimento Imobiliário')])),
                ('status_da_solicitacao', models.CharField(default='Rejeitada', max_length=25, verbose_name=[('em análise', 'Em Análise'), ('rejeitada', 'Rejeitada'), ('aprovada', 'Aprovada')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoteAtribuicaoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('data_de_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('duracao', models.CharField(default='2 Anos', max_length=10)),
                ('id_do_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
