# Generated by Django 4.2.3 on 2023-09-10 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesolicitacaomodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='loteempresamodel',
            name='empresaid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
        ),
        migrations.AddField(
            model_name='loteempresamodel',
            name='loteId',
            field=models.ManyToManyField(to='lotes.lotemodel'),
        ),
        migrations.AddField(
            model_name='lotedetalhemodel',
            name='descricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotedescricaomodel'),
        ),
        migrations.AddField(
            model_name='lotedetalhemodel',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel'),
        ),
        migrations.AddField(
            model_name='loteatribuicaomodel',
            name='id_solicitacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.lotesolicitacaomodel'),
        ),
        migrations.AddField(
            model_name='localizacaolotemodel',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel'),
        ),
        migrations.AddField(
            model_name='localizacaoempresamodel',
            name='EmpresaModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
        ),
        migrations.AddField(
            model_name='historicolotemodel',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
        ),
        migrations.AddField(
            model_name='historicolotemodel',
            name='loteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel'),
        ),
        migrations.AddField(
            model_name='finalidademodel',
            name='loteid',
            field=models.ForeignKey(default='1034e502-7e90-442a-8480-b4443056e4a2', on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel'),
        ),
        migrations.AddField(
            model_name='finalidademodel',
            name='tipo',
            field=models.ForeignKey(default='1034e502-7e90-442a-8480-b4443056e4a2', on_delete=django.db.models.deletion.CASCADE, to='lotes.tipomodel'),
        ),
    ]
