# Generated by Django 4.2.3 on 2023-08-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localizacaolotemodel',
            old_name='loteId',
            new_name='lote',
        ),
    ]
