# Generated by Django 4.2.3 on 2023-08-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotemodel',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='lotemodel',
            name='valor',
        ),
    ]
