# Generated by Django 4.2.3 on 2023-09-10 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotedetalhemodel',
            old_name='lote',
            new_name='loteid',
        ),
        migrations.AddField(
            model_name='loteimage',
            name='loteId',
            field=models.ForeignKey(default="0cb5fa39ca734e74a10923bf69a40eda", on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel'),
            preserve_default=False,
        ),
    ]
