# Generated by Django 4.2.3 on 2023-09-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_alter_lotemodel_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotemodel',
            old_name='localicacaolote',
            new_name='localicacao',
        ),
        migrations.RenameField(
            model_name='lotemodel',
            old_name='tipo',
            new_name='tipolote',
        ),
    ]
