# Generated by Django 4.2.3 on 2023-08-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_rename_loteid_localizacaolotemodel_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localizacaolotemodel',
            old_name='lote',
            new_name='loteId',
        ),
    ]
