# Generated by Django 4.2.3 on 2023-11-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteempresamodel',
            name='loteId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel'),
            preserve_default=False,
        ),
    ]
