# Generated by Django 4.2.3 on 2023-10-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('finalidadeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.tipomodel')),
                ('loteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
