# Generated by Django 4.2.3 on 2023-08-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_rename_lote_localizacaolotemodel_loteid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacaolotemodel',
            name='loteId',
        ),
    ]
