# Generated by Django 4.2.3 on 2023-10-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_solicitacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotesolicitacaomodel',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='lotesolicitacaomodel',
            name='data_solicitacao',
        ),
        migrations.RemoveField(
            model_name='lotesolicitacaomodel',
            name='mes',
        ),
        migrations.DeleteModel(
            name='solicitacao',
        ),
    ]
