# Generated by Django 4.2.3 on 2023-08-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_lotemodel_dimensoes_do_lote_lotemodel_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemodel',
            name='dimensoes_do_lote',
            field=models.CharField(default='Largura x Comprimero', max_length=9),
        ),
        migrations.AddField(
            model_name='lotemodel',
            name='localizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lotes.localizacaolotemodel'),
            preserve_default=False,
        ),
    ]
