# Generated by Django 4.2.3 on 2023-09-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_rename_localicacaolote_lotemodel_localicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteempresamodel',
            name='loteId',
            field=models.ManyToManyField(to='lotes.lotemodel'),
        ),
    ]
