# Generated by Django 4.2.3 on 2023-08-30 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_remove_localizacaolotemodel_loteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacaolotemodel',
            name='loteId',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel'),
        ),
    ]
