# Generated by Django 4.2.3 on 2023-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_lotemodel_dimensoes_do_lote_lotemodel_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotemodel',
            name='data_disponibilidade',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
