# Generated by Django 4.2.3 on 2023-09-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_rename_nome_loteimage_titulo_alter_tipomodel_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteimage',
            name='imagem',
            field=models.ImageField(null=True, upload_to='imagems/lote/'),
        ),
    ]
