# Generated by Django 4.2.3 on 2023-09-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0005_rename_localicacao_lotemodel_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotemodel',
            name='imagem',
            field=models.ImageField(null=True, upload_to='static/imagens/lotes/'),
        ),
    ]
