# Generated by Django 4.2.3 on 2023-09-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0005_alter_loteimage_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalidademodel',
            name='tipo',
        ),
        migrations.AddField(
            model_name='finalidademodel',
            name='tipoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.tipolotemodel'),
        ),
    ]
