# Generated by Django 4.2.3 on 2023-08-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_alter_lotesolicitacaomodel_finalidade_de_utilizacao'),
        ('lotes', '0005_alter_lotemodel_data_disponibilidade'),
    ]

    operations = [
    ]
