# Generated by Django 4.2.3 on 2023-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0005_documentolotemodel_documentotitulomodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentolotemodel',
            name='docucmento',
            field=models.FileField(upload_to='documentos/pdf/'),
        ),
    ]
