# Generated by Django 4.2.3 on 2023-08-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0006_rename_loteid_descricaomodel_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descricaomodel',
            old_name='lote',
            new_name='loteid',
        ),
    ]
