# Generated by Django 4.2.3 on 2023-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0006_alter_documentolotemodel_docucmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentolotemodel',
            name='docucmento',
            field=models.FileField(blank=True, upload_to='documentos/pdf/'),
        ),
    ]
