# Generated by Django 4.2.3 on 2023-09-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0006_alter_lotemodel_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemodel',
            name='descricaoempresa',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
