# Generated by Django 4.2.3 on 2023-09-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0007_lotemodel_descricaoempresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotemodel',
            old_name='descricaoempresa',
            new_name='descricaolote',
        ),
    ]
