# Generated by Django 4.2.3 on 2023-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0007_remove_lotesolicitacaomodel_status_da_solicitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesolicitacaomodel',
            name='status_da_solicitacao',
            field=models.CharField(default='Rejeitada', max_length=25, verbose_name=[('em análise', 'Em Análise'), ('rejeitada', 'Rejeitada'), ('aprovada', 'Aprovada')]),
        ),
        migrations.AlterField(
            model_name='lotesolicitacaomodel',
            name='finalidade_de_utilizacao',
            field=models.CharField(default='Industrial', max_length=25, verbose_name=([('industrial', 'Industrial'), ('comercial', 'Comercial'), ('logistica e armazenamento', 'Logistica e Armazenamento'), ('tecnologia e inovação', 'Tecnologia e Inovação'), ('turismo e hospitalidade', 'Turismo e Hospitalidade'), ('energia', 'Energia'), ('agricultura e agroindústria', 'Agricultura e Agroindústria'), ('comércio internacional', 'Comércio Internacional'), ('indústria de pesca', 'Indústria de Pesca'), ('desenvolvimento imobiliário', 'Desenvolvimento Imobiliário')],)),
        ),
    ]
