# Generated by Django 4.2.3 on 2023-09-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0008_alter_finalidademodel_loteid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalidademodel',
            name='tipoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.tipomodel'),
        ),
        migrations.DeleteModel(
            name='TipoLoteModel',
        ),
    ]
