# Generated by Django 4.2.3 on 2023-08-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0008_lotesolicitacaomodel_status_da_solicitacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotesolicitacaomodel',
            name='finalidade_de_utilizacao',
        ),
        migrations.AlterField(
            model_name='lotesolicitacaomodel',
            name='status_da_solicitacao',
            field=models.CharField(choices=[('em análise', 'Em Análise'), ('rejeitada', 'Rejeitada'), ('aprovada', 'Aprovada')], default='Rejeitada', max_length=25),
        ),
    ]
