# Generated by Django 4.2.3 on 2023-09-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0008_rename_descricaoempresa_lotemodel_descricaolote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotemodel',
            name='descricaolote',
            field=models.TextField(null=True),
        ),
    ]
