# Generated by Django 4.2.3 on 2023-10-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0008_alter_documentolotemodel_docucmento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentolotemodel',
            old_name='docucmento',
            new_name='documento',
        ),
        migrations.AlterField(
            model_name='pagamento_atribuicao',
            name='statuspagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('cancelado', 'cancelado')], default='pago', max_length=50),
        ),
    ]
