# Generated by Django 4.2.3 on 2023-10-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0009_rename_docucmento_documentolotemodel_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotemodel',
            old_name='identificadordolote',
            new_name='codigoLote',
        ),
    ]
