# Generated by Django 4.2.3 on 2023-09-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0009_alter_lotemodel_descricaolote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotemodel',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='localizacaolotemodel',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel'),
        ),
    ]
