# Generated by Django 4.2.3 on 2023-09-10 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0009_alter_finalidademodel_tipoid_delete_tipolotemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalidadeSolicitacaoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('solictacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotesolicitacaomodel')),
                ('tipoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.tipomodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
