# Generated by Django 4.2.3 on 2023-09-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0010_finalidadesolicitacaomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotesolicitacaomodel',
            name='finalidade',
        ),
    ]
