# Generated by Django 4.2.3 on 2023-10-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0010_rename_identificadordolote_lotemodel_codigolote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotesolicitacaomodel',
            name='loteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel', verbose_name='codigoLote'),
        ),
    ]
