# Generated by Django 4.2.3 on 2023-08-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0010_lotesolicitacaomodel_finalidade_de_utilizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotesolicitacaomodel',
            name='data_solicitacao',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
