# Generated by Django 4.2.3 on 2023-09-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0010_remove_lotemodel_localizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotemodel',
            name='imagem',
            field=models.ImageField(default=1, upload_to='imagens/lotes/'),
            preserve_default=False,
        ),
    ]
