# Generated by Django 4.2.3 on 2023-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0011_alter_lotesolicitacaomodel_data_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteatribuicaomodel',
            name='valor_da_atribuicao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loteatribuicaomodel',
            name='duracao',
            field=models.CharField(default='Em meses', max_length=10),
        ),
    ]
