# Generated by Django 4.2.3 on 2023-08-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0012_loteatribuicaomodel_valor_da_atribuicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemodel',
            name='imagem_do_lote',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/lotes/'),
        ),
    ]
