# Generated by Django 4.2.3 on 2023-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0012_alter_lotesolicitacaomodel_loteid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotemodel',
            options={'verbose_name': 'Lote ', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='lotesolicitacaomodel',
            options={'verbose_name': 'Lote Solicitacao', 'verbose_name_plural': 'Solicitacoes de Lotes'},
        ),
        migrations.AddField(
            model_name='lotesolicitacaomodel',
            name='tempo',
            field=models.IntegerField(default=1, verbose_name='Tempo De Requisicao'),
        ),
        migrations.AddField(
            model_name='lotesolicitacaomodel',
            name='valor',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lotemodel',
            name='valor',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='lotemodel',
            table='Lotes',
        ),
        migrations.AlterModelTable(
            name='lotesolicitacaomodel',
            table='Solicitacao',
        ),
    ]
