# Generated by Django 4.2.3 on 2023-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0012_alter_lotemodel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotemodel',
            name='descricaolote',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lotemodel',
            name='identificadordolote',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
