# Generated by Django 4.2.3 on 2023-09-10 22:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0012_rename_solictacao_finalidadesolicitacaomodel_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocalizacaoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('longitude', models.CharField(max_length=35, null=True)),
                ('latitude', models.CharField(max_length=35, null=True)),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
