# Generated by Django 4.2.3 on 2023-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0013_alter_lotemodel_descricaolote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicolotemodel',
            name='data_atribuicao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
