# Generated by Django 4.2.3 on 2023-10-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0013_alter_lotemodel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoModel',
            new_name='TipoLoteModel',
        ),
    ]
