# Generated by Django 4.2.3 on 2023-08-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0013_lotemodel_imagem_do_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotemodel',
            old_name='area_do_lote',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='lotemodel',
            old_name='dimensoes_do_lote',
            new_name='dimensoes',
        ),
        migrations.RenameField(
            model_name='lotemodel',
            old_name='imagem_do_lote',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='lotemodel',
            old_name='status_do_lote',
            new_name='status',
        ),
    ]
