# Generated by Django 4.2.3 on 2023-09-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0014_alter_historicolotemodel_data_atribuicao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento_atribuicao',
            old_name='data_do_pagamento',
            new_name='datapagamento',
        ),
        migrations.RenameField(
            model_name='pagamento_atribuicao',
            old_name='status_do_pagamento',
            new_name='statuspagamento',
        ),
        migrations.RenameField(
            model_name='pagamento_atribuicao',
            old_name='valor_do_pagamento',
            new_name='valorpagamento',
        ),
    ]
