# Generated by Django 4.2.3 on 2023-08-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('lotes', '0014_rename_area_do_lote_lotemodel_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteatribuicaomodel',
            name='id_da_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotemodel',
            name='valor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotesolicitacaomodel',
            name='id_empresa_solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
            preserve_default=False,
        ),
    ]
