# Generated by Django 4.2.3 on 2023-08-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0015_loteatribuicaomodel_id_da_empresa_lotemodel_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotemodel',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
