# Generated by Django 4.2.3 on 2023-09-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0015_rename_data_do_pagamento_pagamento_atribuicao_datapagamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loteatribuicaomodel',
            old_name='data_de_atribuicao',
            new_name='datatribuicao',
        ),
        migrations.RenameField(
            model_name='loteatribuicaomodel',
            old_name='valor_da_atribuicao',
            new_name='valoratribuicao',
        ),
    ]
