# Generated by Django 4.2.3 on 2023-08-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0016_alter_lotemodel_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotemodel',
            name='area',
        ),
    ]
