# Generated by Django 4.2.3 on 2023-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0016_rename_data_de_atribuicao_loteatribuicaomodel_datatribuicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteimage',
            name='imagem',
            field=models.ImageField(upload_to='imagems/lote/'),
        ),
        migrations.AlterField(
            model_name='lotemodel',
            name='imagem',
            field=models.ImageField(null=True, upload_to='imagens/lotes/'),
        ),
    ]
