# Generated by Django 4.2.3 on 2023-08-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0017_remove_lotemodel_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loteatribuicaomodel',
            old_name='id_da_empresa',
            new_name='id_empresa',
        ),
        migrations.RenameField(
            model_name='loteatribuicaomodel',
            old_name='id_do_lote',
            new_name='id_lote',
        ),
        migrations.RenameField(
            model_name='lotemodel',
            old_name='valor',
            new_name='valor_do_lote',
        ),
        migrations.AddField(
            model_name='loteatribuicaomodel',
            name='id_solicitacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.lotesolicitacaomodel'),
        ),
    ]
