# Generated by Django 4.2.3 on 2023-08-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0018_rename_id_da_empresa_loteatribuicaomodel_id_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loteatribuicaomodel',
            old_name='id_empresa',
            new_name='nif_empresa',
        ),
        migrations.RenameField(
            model_name='lotesolicitacaomodel',
            old_name='id_empresa_solicitante',
            new_name='nif_empresa_solicitante',
        ),
        migrations.AddField(
            model_name='lotemodel',
            name='informacoes_de_infraestrutura',
            field=models.TextField(default='Ta tudo limpo aqui!'),
            preserve_default=False,
        ),
    ]
