# Generated by Django 4.2.3 on 2023-08-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0019_rename_id_empresa_loteatribuicaomodel_nif_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loteatribuicaomodel',
            old_name='nif_empresa',
            new_name='id_empresa',
        ),
        migrations.RenameField(
            model_name='lotesolicitacaomodel',
            old_name='nif_empresa_solicitante',
            new_name='id_empresa_solicitante',
        ),
    ]
