# Generated by Django 4.2.3 on 2023-08-17 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0030_alter_empresamodel_principais_funcionarios'),
        ('lotes', '0020_rename_nif_empresa_loteatribuicaomodel_id_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_atribuicao', models.DateField()),
                ('data_saida', models.DateField()),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel')),
            ],
        ),
    ]
