# Generated by Django 4.2.3 on 2023-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0023_rename_id_empresa_historicolotemodel_nif_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotemodel',
            name='dimensoes',
        ),
        migrations.AddField(
            model_name='lotemodel',
            name='comprimento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lotemodel',
            name='largura',
            field=models.IntegerField(default=0),
        ),
    ]
