# Generated by Django 4.2.3 on 2023-08-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0024_remove_lotemodel_dimensoes_lotemodel_comprimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteatribuicaomodel',
            name='data_de_atribuicao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lotemodel',
            name='data_disponibilidade',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lotesolicitacaomodel',
            name='data_solicitacao',
            field=models.DateField(auto_created=True),
        ),
    ]
