# Generated by Django 4.2.3 on 2023-08-29 08:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0030_alter_empresamodel_principais_funcionarios'),
        ('lotes', '0025_alter_loteatribuicaomodel_data_de_atribuicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemodel',
            name='empresaID',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
        ),
        migrations.CreateModel(
            name='Descricaomodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
                ('detalhes', models.TextField()),
                ('loteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lotemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
