# Generated by Django 4.2.3 on 2023-08-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0026_lotemodel_empresaid_descricaomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotemodel',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='localizacaolotemodel',
            name='latitude',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='localizacaolotemodel',
            name='longitude',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
