# Generated by Django 4.2.3 on 2023-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0027_rename_descricao_lotemodel_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotesolicitacaomodel',
            name='status_da_solicitacao',
            field=models.CharField(choices=[('em análise', 'Em Análise'), ('rejeitada', 'Rejeitada'), ('aprovada', 'Aprovada')], default='Em Análise', max_length=25),
        ),
    ]
