# Generated by Django 4.2.3 on 2023-08-29 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0033_remove_empresamodel_principais_funcionarios_and_more'),
        ('lotes', '0029_remove_lotemodel_localizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotemodel',
            name='empresaID',
        ),
        migrations.CreateModel(
            name='LoteEmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('empresaid', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel')),
                ('loteId', models.ManyToManyField(default=True, to='lotes.lotemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
