# Generated by Django 4.2.3 on 2023-09-10 00:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosEmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('caminho', models.FileField(upload_to='documentos/pdf/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentosModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=55)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=55)),
                ('funcionarios', models.IntegerField(null=True)),
                ('nif', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imagens/logo/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.IntegerField(default=0, unique=True)),
                ('detalhes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectorEmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('actividade', models.CharField(max_length=125)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacaoGeralModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=50)),
                ('tipo_notificacao', models.CharField(max_length=50)),
                ('assunto', models.TextField(default='')),
                ('data', models.DateField(default=0)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='', max_length=50)),
                ('nif_empresa', models.ManyToManyField(to='empresas.empresamodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacaoEmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=50)),
                ('tipo_notificacao', models.CharField(max_length=50)),
                ('assunto_empresa', models.TextField(default='')),
                ('data', models.DateField(default=0)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='', max_length=50)),
                ('nif_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuncionariosModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('first_name', models.CharField(default='Joao', max_length=55)),
                ('last_name', models.CharField(default='Paulo', max_length=55)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Nao_Binario')], default='Nao_binario', max_length=50)),
                ('idade', models.PositiveSmallIntegerField()),
                ('bi', models.CharField(max_length=15, unique=True)),
                ('cargo', models.CharField(default='Cosinheiro', max_length=55)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_telefone', models.IntegerField(default=927860898, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagens/fotos/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='actividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.sectorempresamodel'),
        ),
    ]
