# Generated by Django 4.2.3 on 2023-08-14 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('nome_da_empresa', models.CharField(max_length=55)),
                ('numero_de_funcionarios', models.IntegerField()),
                ('principais_integrantes', models.IntegerField()),
                ('nif', models.CharField(max_length=15)),
                ('dono_da_empresa', models.CharField(max_length=55)),
                ('sector_actividade', models.CharField(max_length=55)),
                ('logo', models.ImageField(upload_to='', verbose_name='static/images/logo/')),
                ('localizacao_actual', models.CharField(default='Nenhuma', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
