# Generated by Django 4.2.3 on 2023-09-10 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='localizacaoLote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.localizacaolotemodel', verbose_name='Coordenadas dos lotes'),
        ),
        migrations.AddField(
            model_name='documentosempresamodel',
            name='documentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.documentosmodel'),
        ),
        migrations.AddField(
            model_name='documentosempresamodel',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmpresaModel', to='empresas.empresamodel'),
        ),
    ]
