# Generated by Django 4.2.3 on 2023-08-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_funcionariosmodel_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariosmodel',
            name='cargo',
            field=models.CharField(default='Cosinheiro', max_length=55),
        ),
    ]
