# Generated by Django 4.2.3 on 2023-08-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_funcionariosmodel_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresamodel',
            name='principais_funcionarios',
        ),
        migrations.RemoveField(
            model_name='funcionariosmodel',
            name='nome',
        ),
        migrations.AddField(
            model_name='funcionariosmodel',
            name='nomde_do_funcionario',
            field=models.CharField(default='Joao', max_length=55),
        ),
        migrations.AddField(
            model_name='funcionariosmodel',
            name='nome_da_empresa',
            field=models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
        ),
        migrations.AddField(
            model_name='funcionariosmodel',
            name='sexo',
            field=models.CharField(default='Nao binario', max_length=50, verbose_name=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao binario', 'Nao Binario')]),
        ),
    ]
