# Generated by Django 4.2.3 on 2023-08-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_empresamodel_principais_funcionarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariosmodel',
            name='nome_da_empresa',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
        ),
    ]
