# Generated by Django 4.2.3 on 2023-08-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_funcionariosmodel_nome_da_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariosmodel',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='funcionariosmodel',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='funcionariosmodel',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='funcionariosmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
