# Generated by Django 4.2.3 on 2023-08-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_funcionariosmodel_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/logo/'),
        ),
        migrations.AlterField(
            model_name='funcionariosmodel',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Nao_Binario')], default='Nao_binario', max_length=50),
        ),
    ]
