# Generated by Django 4.2.3 on 2023-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_rename_nomde_do_funcionario_funcionariosmodel_nome_do_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='numero_de_funcionarios',
            field=models.IntegerField(null=True),
        ),
    ]
