# Generated by Django 4.2.3 on 2023-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_empresamodel_numero_de_funcionarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresamodel',
            old_name='email',
            new_name='email_da_empresa',
        ),
        migrations.RenameField(
            model_name='funcionariosmodel',
            old_name='nome_da_empresa',
            new_name='empresa',
        ),
        migrations.AddField(
            model_name='funcionariosmodel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/foto'),
        ),
        migrations.AddField(
            model_name='funcionariosmodel',
            name='numero_telefone',
            field=models.IntegerField(default=927860898, unique=True),
        ),
    ]
