# Generated by Django 4.2.3 on 2023-08-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_rename_email_empresamodel_email_da_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariosmodel',
            name='numero_telefone',
            field=models.IntegerField(unique=True),
        ),
    ]
