# Generated by Django 4.2.3 on 2023-08-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_alter_funcionariosmodel_numero_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='telefone',
            field=models.IntegerField(default=927860898, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionariosmodel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/fotos/'),
        ),
        migrations.AlterField(
            model_name='funcionariosmodel',
            name='numero_telefone',
            field=models.IntegerField(default=927860898, unique=True),
        ),
    ]
