# Generated by Django 4.2.3 on 2023-08-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_empresamodel_telefone_alter_funcionariosmodel_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='telefone',
            field=models.IntegerField(default=927860898),
        ),
    ]
