# Generated by Django 4.2.3 on 2023-08-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_alter_empresamodel_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='telefone',
            field=models.IntegerField(default=927860898, unique=True),
        ),
    ]
