# Generated by Django 4.2.3 on 2023-08-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_alter_empresamodel_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariosmodel',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='principais_funcionarios',
            field=models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='empresas.funcionariosmodel'),
        ),
    ]
