# Generated by Django 4.2.3 on 2023-08-15 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0024_remove_empresamodel_localizacao_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens/logo/'),
        ),
        migrations.AlterField(
            model_name='empresamodel',
            name='principais_funcionarios',
            field=models.ForeignKey(default=0, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.funcionariosmodel', unique=True),
        ),
    ]
