# Generated by Django 4.2.3 on 2023-08-15 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0026_alter_empresamodel_principais_funcionarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='principais_funcionarios',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.funcionariosmodel'),
        ),
    ]
