# Generated by Django 4.2.3 on 2023-08-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0030_alter_empresamodel_principais_funcionarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionariosmodel',
            old_name='nome_do_funcionario',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='funcionariosmodel',
            name='last_name',
            field=models.CharField(default='Paulo', max_length=55),
        ),
    ]
