# Generated by Django 4.2.3 on 2023-08-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0032_notificacaogeralmodel_notificacaoempresamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresamodel',
            name='principais_funcionarios',
        ),
        migrations.AddField(
            model_name='funcionariosmodel',
            name='empresaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresamodel'),
            preserve_default=False,
        ),
    ]
