# Generated by Django 4.2.3 on 2023-09-04 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0033_remove_empresamodel_principais_funcionarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentosEmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('caminho', models.FileField(upload_to='static/documentos/pdf/')),
                ('documentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.documentosmodel')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmpresaModel', to='empresas.empresamodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
