# Generated by Django 4.2.3 on 2023-09-04 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0035_alter_documentosmodel_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonoEmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('first_nome', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectorEmpresaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('actividade', models.CharField(max_length=125)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='empresamodel',
            old_name='email_da_empresa',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='empresamodel',
            old_name='numero_de_funcionarios',
            new_name='funcionarios',
        ),
        migrations.RenameField(
            model_name='empresamodel',
            old_name='dono_da_empresa',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='empresamodel',
            name='nome_da_empresa',
        ),
        migrations.RemoveField(
            model_name='empresamodel',
            name='sector_actividade',
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='detalhes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.donoempresamodel'),
            preserve_default=False,
        ),
    ]
