# Generated by Django 4.2.3 on 2023-09-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0037_remove_empresamodel_dono_delete_donoempresamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionariosmodel',
            old_name='empresaId',
            new_name='empresa',
        ),
    ]
