# Generated by Django 4.2.3 on 2023-09-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0038_rename_empresaid_funcionariosmodel_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='actividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.sectorempresamodel'),
            preserve_default=False,
        ),
    ]
