# Generated by Django 4.2.3 on 2023-09-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0039_empresamodel_actividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosempresamodel',
            name='caminho',
            field=models.FileField(upload_to='documentos/pdf/'),
        ),
        migrations.AlterField(
            model_name='empresamodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/logo/'),
        ),
        migrations.AlterField(
            model_name='funcionariosmodel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/fotos/'),
        ),
    ]
